// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDepartment = "department"

// Department mapped from table <department>
type Department struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name      *string        `gorm:"column:name;type:varchar(191)" json:"name"`
	Status    *int64         `gorm:"column:status;type:bigint" json:"status"`
	Sort      *int64         `gorm:"column:sort;type:bigint" json:"sort"`
	Principal *string        `gorm:"column:principal;type:varchar(191)" json:"principal"`
	ParentID  *int64         `gorm:"column:parent_id;type:bigint unsigned;index:fk_department_departments,priority:1" json:"parent_id"`
	Phone     *string        `gorm:"column:phone;type:varchar(191)" json:"phone"`
	Email     *string        `gorm:"column:email;type:varchar(191)" json:"email"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_department_deleted_at,priority:1" json:"deleted_at"`
}

// TableName Department's table name
func (*Department) TableName() string {
	return TableNameDepartment
}
