// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMenuAPI = "menu_apis"

// MenuAPI mapped from table <menu_apis>
type MenuAPI struct {
	MenuID int64 `gorm:"column:menu_id;type:bigint unsigned;primaryKey" json:"menu_id"`
	APIID  int64 `gorm:"column:api_id;type:bigint unsigned;primaryKey;index:fk_menu_apis_api,priority:1" json:"api_id"`
}

// TableName MenuAPI's table name
func (*MenuAPI) TableName() string {
	return TableNameMenuAPI
}
