// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMenu = "menu"

// Menu mapped from table <menu>
type Menu struct {
	ID            int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name          *string        `gorm:"column:name;type:varchar(191)" json:"name"`
	Path          *string        `gorm:"column:path;type:varchar(191)" json:"path"`
	Component     *string        `gorm:"column:component;type:varchar(191)" json:"component"`
	Redirect      *string        `gorm:"column:redirect;type:varchar(191)" json:"redirect"`
	Layout        *int64         `gorm:"column:layout;type:bigint" json:"layout"`
	Icon          *string        `gorm:"column:icon;type:varchar(191)" json:"icon"`
	Type          *int64         `gorm:"column:type;type:bigint" json:"type"`
	Remark        *string        `gorm:"column:remark;type:longtext" json:"remark"`
	RequestURL    *string        `gorm:"column:request_url;type:longtext" json:"request_url"`
	RequestMethod *string        `gorm:"column:request_method;type:longtext" json:"request_method"`
	Link          *string        `gorm:"column:link;type:longtext" json:"link"`
	Identifier    *int64         `gorm:"column:identifier;type:bigint" json:"identifier"`
	Sort          *int64         `gorm:"column:sort;type:bigint" json:"sort"`
	Hidden        *int64         `gorm:"column:hidden;type:bigint" json:"hidden"`
	Cache         *int64         `gorm:"column:cache;type:bigint" json:"cache"`
	Fixed         *int64         `gorm:"column:fixed;type:bigint" json:"fixed"`
	Pid           *int64         `gorm:"column:pid;type:bigint unsigned;index:fk_menu_children,priority:1" json:"pid"`
	CreatedAt     *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt     *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_menu_deleted_at,priority:1" json:"deleted_at"`
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
