// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserRole = "user_role"

// UserRole mapped from table <user_role>
type UserRole struct {
	RoleID int64 `gorm:"column:role_id;type:bigint unsigned;primaryKey" json:"role_id"`
	UserID int64 `gorm:"column:user_id;type:bigint unsigned;primaryKey;index:fk_user_role_user,priority:1" json:"user_id"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
