// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"github.com/NSObjects/echo-admin/internal/api/data/model"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&model.Menu{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.Menu{}) fail: %s", err)
	}
}

func Test_menuQuery(t *testing.T) {
	menu := newMenu(db)
	menu = *menu.As(menu.TableName())
	_do := menu.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(menu.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <menu> fail:", err)
		return
	}

	_, ok := menu.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from menu success")
	}

	err = _do.Create(&model.Menu{})
	if err != nil {
		t.Error("create item in table <menu> fail:", err)
	}

	err = _do.Save(&model.Menu{})
	if err != nil {
		t.Error("create item in table <menu> fail:", err)
	}

	err = _do.CreateInBatches([]*model.Menu{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <menu> fail:", err)
	}

	_, err = _do.Select(menu.ALL).Take()
	if err != nil {
		t.Error("Take() on table <menu> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <menu> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <menu> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <menu> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.Menu{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <menu> fail:", err)
	}

	_, err = _do.Select(menu.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <menu> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <menu> fail:", err)
	}

	_, err = _do.Select(menu.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <menu> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <menu> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <menu> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <menu> fail:", err)
	}

	_, err = _do.ScanByPage(&model.Menu{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <menu> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <menu> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <menu> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <menu> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <menu> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <menu> fail:", err)
	}
}

var MenuGetByIdTestCase = []TestCase{}

func Test_menu_GetById(t *testing.T) {
	menu := newMenu(db)
	do := menu.WithContext(context.Background()).Debug()

	for i, tt := range MenuGetByIdTestCase {
		t.Run("GetById_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.GetById(tt.Input.Args[0].(int))
			assert(t, "GetById", res1, tt.Expectation.Ret[0])
			assert(t, "GetById", res2, tt.Expectation.Ret[1])
		})
	}
}

var MenuDeleteByIDTestCase = []TestCase{}

func Test_menu_DeleteByID(t *testing.T) {
	menu := newMenu(db)
	do := menu.WithContext(context.Background()).Debug()

	for i, tt := range MenuDeleteByIDTestCase {
		t.Run("DeleteByID_"+strconv.Itoa(i), func(t *testing.T) {
			res1 := do.DeleteByID(tt.Input.Args[0].(int64))
			assert(t, "DeleteByID", res1, tt.Expectation.Ret[0])
		})
	}
}
